### ISSUE TITLE
No tests discovered on macOS Tahoe

### ISSUE THREAD

**Issue by mturnock** [mattstevens/xcode-googletest#12]
I'm running macOS 26 and I have an issue where suddenly no google tests are discovered.  Everything still works fine on the build server, and no one else on the team is reporting a problem.

Test discovery fails because in GoogleTestLoader::load the bundle is already loaded (bundle.loaded == true), so the callback registered for NSBundleDidLoadNotification never fires.  If I call registerTestClasses() in GoogleTestLoader::load() it finds nothing because the static initialisers haven't run yet.

If I manually run registerTestClasses() at a later point, when the static initialisers for the test classes have run, then the tests are discovered fine.  I want't able to find a sensible place to inject this call, so it's a bit of a hack at the moment.

Has anyone else come across this?  Does anyone know why it might be happening? Does anyone have a good suggestion for what event to run registerTestClasses() on, or how to inject a call to it from somewhere sensible?

**Comment by mturnock** [comment]
I took another look at the issue this morning, I'm thinking something like this:

```
+ (void)load {
    NSBundle *bundle = [NSBundle bundleForClass:self];
    [[NSNotificationCenter defaultCenter] addObserverForName:NSBundleDidLoadNotification object:bundle queue:nil usingBlock:^(NSNotification *notification) {
        [self registerTestClassesOnce];
    }];
    dispatch_async(dispatch_get_main_queue(), ^{
        [self registerTestClassesOnce];
    });
}

+ (void)registerTestClassesOnce {
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        [self registerTestClasses];
    });
}
```

**Comment by eugenegff** [comment]
Also GoogleTestLoader can be made principal class of the test bundle, as instance of principal class is created by XCTest infrastructure, but dispatch_async(dispatch_get_main_queue(),... is called sooner.

**Comment by stevebaxter** [comment]
Just run into this. The fix above works in some cases, but in others the tests run before `dispatch_async()` runs, so we still don't get any tests.

**Comment by stevebaxter** [comment]
I had to make `GoogleTestLoader` the principal class of my test bundles and add:

```
/**
 * Register our test classes before any tests run. For this to work,`GoogleTestLoader` must
 * be the principle class of the bundle.
 */
- (instancetype)init
{
    self = [super init];
    
    if (self)
    {
        [GoogleTestLoader registerTestClassesOnce];
    }

    return self;
}
```

This then runs at the right point.

**Comment by eugenegff** [comment]
Fix merged into https://github.com/eugenegff/xcode-googletest fork

**Comment by jmd-dk** [comment]
@eugenegff Nice, with your changes I indeed get Xcode to run my tests, but they still do not show up in the Test Navigator on the left. Any idea why? Can it be fixed? Thanks

**Comment by eugenegff** [comment]
> [@eugenegff](https://github.com/eugenegff) Nice, with your changes I indeed get Xcode to run my tests, but they still do not show up in the Test Navigator on the left. Any idea why? Can it be fixed? Thanks

Did you set GoogleTestLoader as principal class? Break in -[GoogleTestLoader init] happens? On that line:

```
- (instancetype)init
{
    self = [super init];
    if (self) {
        [GoogleTestLoader registerTestClassesOnce]; // GoogleTestLoader should be made principal
    }
    return self;
}

```
